label: "excess_logret_5d_bin"
horizon_days: 5
embargo_days: 5
n_splits: 5
macro_symbols:
  - "^TNX"
  - "HYG"
  - "LQD"
  - "DXY"
  - "EURUSD=X"
  - "USDJPY=X"
  - "GBPUSD=X"
  - "CL=F"
  - "BZ=F"
  - "GC=F"
  - "HG=F"
  - "SPY"
  - "QQQ"
  - "IWM"
  - "^STOXX50E"
  - "EZU"
  - "^VIX"
  - "MOVE"
params:
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 6
  min_child_weight: 4
  gamma: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.3
  reg_lambda: 0.3
  random_state: 42
  n_jobs: -1
calibration: "isotonic"
early_stopping_rounds: 100
